### PR TITLE
Added Hungarian translate

### PR DESCRIPTION
**Pull request by wasyady**
I would like to help you with a Hungarian translation! 👍

### CODE REVIEW

**Comment by neatek** [comment]
here some errors...

```
	"gv_no"
	{
 		"en" "No" <=== HERE "en"
 		"en" "Nem" <=== AND HERE "en"
 		"ru" "Нет"
 		"fr" "Non"
 		"es" "No"
 	}
```


double "en" and "en"

**Comment by neatek** [comment]
AND HERE 

```
+	"gv_mute_title_question"
 +	{
 +		"#format" "{1:s}"
 +		"en" "MUTE {1}?"
 +		"en" "{1} NÉMÍTÁSA?"
 +		"ru" "ЗАМЬЮТИТЬ {1}?"
 +		"fr" "MUTE {1}?"
 +		"es" "MUTEAR A {1}?"
 +	}
```

**Comment by wasyady** [comment]
Corrected!

Thanks for notice!

**Comment by neatek** [comment]
Please, fix latest mistake.

**Comment by wasyady** [comment]
I think I've fixed all the problems!

**Pull request merged**
